### PR TITLE
Register providers before checking name availability

### PR DESCRIPTION
**Pull request by nturinski**
Fixes https://github.com/microsoft/vscode-azurefunctions/issues/3269

This issue is happening with _NEW_ subscriptions. I don't think the trial/pay-as-you go is actually the issue here. The storage provider isn't registered, but we are calling `isRelatedNameAvailable` for storage accounts before the provider is verified to be registered.

Since it's school season, I think we're seeing an influx of these issues due to the fact that classes are starting up and students are registering trial accounts.

### CODE REVIEW

**Comment by alexweininger** [comment]
Do you know if this was a regression?

**Review by alexweininger — APPROVED** [review]
Although I don't think we've seen similar issues in other repos, we should check if we need to make this change in other places we use `VerifyProvidersStep`.

edit: also nice work 🚀

**Comment by nturinski** [comment]
> Do you know if this was a regression?

I don't think so. We haven't changed anything with the generating related name code. It could be something changed on the Azure Storage that requires the provider be registered in order to call `checkNameAvailability`? Or it _could_ be something to do with trial accounts?

**Comment by IHVH** [comment]
> Fixes #3269
> 
...
> Since it's school season, I think we're seeing an influx of these issues due to the fact that classes are starting up and students are registering trial accounts.

It's really, this subscription is used for student learning.

**Comment by alexweininger** [comment]
@IHVH 

A fix for this bug has been released in https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.8.0, please let us know if you're still experiencing this issue.

**Comment by IHVH** [comment]
I'm not sure if #3269 is related to my question #3363
But yes my problem is still there
Thanks @alexweininger !

**Pull request merged**
