### PR TITLE
add debug argument when start function host

### PR DESCRIPTION
**Pull request by jdneo**
The Maven Function Archetype update for `local.settings.json` is here: https://github.com/Microsoft/azure-maven-archetypes/pull/34

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
Is this really necessary or is it just a workaround until the functions cli releases the fix for this bug? https://github.com/Azure/azure-functions-core-tools/issues/557

**Comment by jdneo** [comment]
@pragnagopa Could you please help confirm this? Thank you.

The question is:

Now users need to explicitly set `--language-worker -- "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"` to start function host if he wants to debug. Is this only needed in 2.0.1-beta.31. Or the later versions of function cli will also follow this?

**Comment by pragnagopa** [comment]
Runtime and cli  with this change is part of current release. Will be in production soon. Yes starting with current release uses need to explicitly specify debug command

**Comment by jdneo** [comment]
@pragnagopa Thank you for the information.

**Comment by EricJizbaMSFT** [comment]
@pragnagopa is this change documented somewhere? @jdneo's change will only help new users - existing users will have to manually update otherwise debugging will be broken.

I saw this https://github.com/Azure/app-service-announcements/issues/122, but didn't see anything in particular about debugging

**Comment by pragnagopa** [comment]
Thanks for the reminder @EricJizbaMSFT . This change is part of the release we are prepping now.  Azure/app-service-announcements#122, is a heads up for a future release. I will update the release notes for the current release.

**Pull request merged**
